version: '3'

services:
  db:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

  app:
    container_name: pms
    image: ceey/pms
    env_file:
      - ./env/application
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - ./log:/pms/log

volumes:
  db-data:
