version: '3'

services:
  db:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - 3306:3306
    restart: always
    volumes:
      - db-data:/var/lib/mysql

  pms:
    container_name: pms
    image: ceeyweb/simulador:${VERSION:-latest}
    env_file:
      - ./env/application
    depends_on:
      - db
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./log:/pms/log

volumes:
  db-data:
